name: Selenium TestNG Parallel Multi-Browser CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: test-platform/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('test-platform/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install npm dependencies for test-platform
        run: |
          cd test-platform
          npm install

      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Run Selenium+Cucumber+TestNG tests in parallel for all browsers
        run: |
          export CI=true
          chmod +x run-platform-tests-and-allure.sh
          ./run-platform-tests-and-allure.sh

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
      
      - name: Print Allure Report Download Link
        if: always()
        run: |
          echo "Download the Allure report from the workflow run's 'Artifacts' section: allure-report.zip"
